"""添加商品表缺失字段

Revision ID: ad852d15f794
Revises: 3520cda48e53
Create Date: 2025-09-28 15:19:07.554371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ad852d15f794'
down_revision: Union[str, Sequence[str], None] = '3520cda48e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_orders_id'), table_name='draft_orders')
    op.drop_table('draft_orders')
    op.drop_index(op.f('ix_simple_orders_id'), table_name='simple_orders')
    op.drop_table('simple_orders')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_simple_products_id'), table_name='simple_products')
    op.drop_table('simple_products')
    op.drop_index(op.f('ix_simple_cart_id'), table_name='simple_cart')
    op.drop_table('simple_cart')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_watch_records_id'), table_name='watch_records')
    op.drop_table('watch_records')
    op.drop_index(op.f('ix_consultations_consultation_number'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_expert_schedules_id'), table_name='expert_schedules')
    op.drop_table('expert_schedules')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_consultation_messages_id'), table_name='consultation_messages')
    op.drop_table('consultation_messages')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_expert_reviews_id'), table_name='expert_reviews')
    op.drop_table('expert_reviews')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_experts_id'), table_name='experts')
    op.drop_index(op.f('ix_experts_name'), table_name='experts')
    op.drop_table('experts')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_simple_order_items_id'), table_name='simple_order_items')
    op.drop_table('simple_order_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_order_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('product_price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simple_order_items_id'), 'simple_order_items', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('avatar', sa.VARCHAR(), nullable=True),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('birthday', sa.DATETIME(), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=11), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('is_phone_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=1)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=16), nullable=False),
    sa.Column('duration', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('is_free', sa.BOOLEAN(), nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), nullable=True),
    sa.Column('instructor', sa.VARCHAR(), nullable=True),
    sa.Column('total_lessons', sa.INTEGER(), nullable=True),
    sa.Column('total_duration', sa.INTEGER(), nullable=True),
    sa.Column('audit_status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('submitted_by', sa.VARCHAR(), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('audit_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('experts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('level', sa.VARCHAR(length=12), nullable=True),
    sa.Column('category', sa.VARCHAR(length=11), nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('specialties', sqlite.JSON(), nullable=True),
    sa.Column('qualifications', sqlite.JSON(), nullable=True),
    sa.Column('education', sa.TEXT(), nullable=True),
    sa.Column('experience_years', sa.INTEGER(), nullable=True),
    sa.Column('hospital_affiliation', sa.VARCHAR(), nullable=True),
    sa.Column('department', sa.VARCHAR(), nullable=True),
    sa.Column('services_offered', sqlite.JSON(), nullable=True),
    sa.Column('text_price', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('voice_price', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('video_price', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('working_hours', sqlite.JSON(), nullable=True),
    sa.Column('timezone', sa.VARCHAR(), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.Column('consultation_count', sa.INTEGER(), nullable=True),
    sa.Column('total_rating_count', sa.INTEGER(), nullable=True),
    sa.Column('response_time', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('wechat', sa.VARCHAR(), nullable=True),
    sa.Column('personal_statement', sa.TEXT(), nullable=True),
    sa.Column('treatment_philosophy', sa.TEXT(), nullable=True),
    sa.Column('successful_cases', sa.TEXT(), nullable=True),
    sa.Column('audit_status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('submitted_by', sa.VARCHAR(), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('audit_notes', sa.TEXT(), nullable=True),
    sa.Column('last_online', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experts_name'), 'experts', ['name'], unique=False)
    op.create_index(op.f('ix_experts_id'), 'experts', ['id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('progress', sa.FLOAT(), nullable=True),
    sa.Column('completed_lessons', sa.INTEGER(), nullable=True),
    sa.Column('total_watch_time', sa.INTEGER(), nullable=True),
    sa.Column('last_watched_lesson_id', sa.INTEGER(), nullable=True),
    sa.Column('enrolled_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['last_watched_lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_table('expert_reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('expert_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('consultation_id', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('service_attitude', sa.FLOAT(), nullable=True),
    sa.Column('professional_level', sa.FLOAT(), nullable=True),
    sa.Column('response_speed', sa.FLOAT(), nullable=True),
    sa.Column('is_anonymous', sa.BOOLEAN(), nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), nullable=True),
    sa.Column('admin_reply', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_reviews_id'), 'expert_reviews', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_number', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('shipping_fee', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.VARCHAR(length=15), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=10), nullable=True),
    sa.Column('payment_id', sa.VARCHAR(), nullable=True),
    sa.Column('shipping_address', sqlite.JSON(), nullable=True),
    sa.Column('shipping_name', sa.VARCHAR(), nullable=True),
    sa.Column('shipping_phone', sa.VARCHAR(), nullable=True),
    sa.Column('tracking_number', sa.VARCHAR(), nullable=True),
    sa.Column('courier_company', sa.VARCHAR(), nullable=True),
    sa.Column('user_note', sa.TEXT(), nullable=True),
    sa.Column('admin_note', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.Column('shipped_at', sa.DATETIME(), nullable=True),
    sa.Column('delivered_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=1)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('consultation_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('consultation_id', sa.INTEGER(), nullable=False),
    sa.Column('sender_type', sa.VARCHAR(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=True),
    sa.Column('message_type', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('attachments', sqlite.JSON(), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_messages_id'), 'consultation_messages', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=14), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('discount', sa.NUMERIC(precision=3, scale=2), nullable=True),
    sa.Column('stock_quantity', sa.INTEGER(), nullable=True),
    sa.Column('min_stock_alert', sa.INTEGER(), nullable=True),
    sa.Column('images', sqlite.JSON(), nullable=True),
    sa.Column('specifications', sqlite.JSON(), nullable=True),
    sa.Column('features', sqlite.JSON(), nullable=True),
    sa.Column('usage_instructions', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=12), nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), nullable=True),
    sa.Column('is_common', sa.BOOLEAN(), nullable=True),
    sa.Column('is_prescription_required', sa.BOOLEAN(), nullable=True),
    sa.Column('audit_status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('submitted_by', sa.VARCHAR(), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('audit_notes', sa.TEXT(), nullable=True),
    sa.Column('seo_title', sa.VARCHAR(), nullable=True),
    sa.Column('seo_keywords', sa.VARCHAR(), nullable=True),
    sa.Column('seo_description', sa.TEXT(), nullable=True),
    sa.Column('sales_count', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.Column('review_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('entity_type', sa.TEXT(), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('entity_title', sa.TEXT(), nullable=True),
    sa.Column('action', sa.TEXT(), nullable=False),
    sa.Column('old_status', sa.TEXT(), nullable=True),
    sa.Column('new_status', sa.TEXT(), nullable=False),
    sa.Column('operator_id', sa.INTEGER(), nullable=False),
    sa.Column('operator_name', sa.TEXT(), nullable=False),
    sa.Column('operator_role', sa.TEXT(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('attachment', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.TEXT(), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expert_schedules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('expert_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('start_time', sa.VARCHAR(), nullable=False),
    sa.Column('end_time', sa.VARCHAR(), nullable=False),
    sa.Column('max_consultations', sa.INTEGER(), nullable=True),
    sa.Column('current_consultations', sa.INTEGER(), nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_schedules_id'), 'expert_schedules', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('consultation_number', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('expert_id', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=5), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('symptoms', sa.TEXT(), nullable=True),
    sa.Column('duration', sa.VARCHAR(), nullable=True),
    sa.Column('medical_history', sa.TEXT(), nullable=True),
    sa.Column('current_medications', sa.TEXT(), nullable=True),
    sa.Column('additional_info', sa.TEXT(), nullable=True),
    sa.Column('ai_response', sa.TEXT(), nullable=True),
    sa.Column('ai_confidence', sa.FLOAT(), nullable=True),
    sa.Column('ai_suggestions', sqlite.JSON(), nullable=True),
    sa.Column('expert_notes', sa.TEXT(), nullable=True),
    sa.Column('expert_diagnosis', sa.TEXT(), nullable=True),
    sa.Column('expert_recommendations', sa.TEXT(), nullable=True),
    sa.Column('prescription', sqlite.JSON(), nullable=True),
    sa.Column('follow_up_required', sa.BOOLEAN(), nullable=True),
    sa.Column('follow_up_date', sa.DATETIME(), nullable=True),
    sa.Column('attachments', sqlite.JSON(), nullable=True),
    sa.Column('voice_messages', sqlite.JSON(), nullable=True),
    sa.Column('video_call_id', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('payment_id', sa.VARCHAR(), nullable=True),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.Column('user_rating', sa.FLOAT(), nullable=True),
    sa.Column('user_feedback', sa.TEXT(), nullable=True),
    sa.Column('expert_rating', sa.FLOAT(), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('admin_notes', sa.TEXT(), nullable=True),
    sa.Column('quality_score', sa.FLOAT(), nullable=True),
    sa.Column('response_time', sa.INTEGER(), nullable=True),
    sa.Column('consultation_duration', sa.INTEGER(), nullable=True),
    sa.Column('message_count', sa.INTEGER(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_id'), 'consultations', ['id'], unique=False)
    op.create_index(op.f('ix_consultations_consultation_number'), 'consultations', ['consultation_number'], unique=1)
    op.create_table('watch_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), nullable=False),
    sa.Column('watch_time', sa.INTEGER(), nullable=True),
    sa.Column('last_position', sa.INTEGER(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_records_id'), 'watch_records', ['id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('video_url', sa.VARCHAR(), nullable=True),
    sa.Column('video_id', sa.VARCHAR(), nullable=True),
    sa.Column('file_id', sa.VARCHAR(), nullable=True),
    sa.Column('cover_url', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), nullable=True),
    sa.Column('is_free', sa.BOOLEAN(), nullable=True),
    sa.Column('transcript', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_table('simple_cart',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simple_cart_id'), 'simple_cart', ['id'], unique=False)
    op.create_table('simple_products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('images', sqlite.JSON(), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simple_products_id'), 'simple_products', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(), nullable=False),
    sa.Column('product_image', sa.VARCHAR(), nullable=True),
    sa.Column('product_specifications', sqlite.JSON(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('selected', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.create_table('simple_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('shipping_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('shipping_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('shipping_address', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_simple_orders_id'), 'simple_orders', ['id'], unique=False)
    op.create_table('draft_orders',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('items_json', sqlite.JSON(), nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('from_source', sa.VARCHAR(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_orders_id'), 'draft_orders', ['id'], unique=False)
    # ### end Alembic commands ###
